import React, { useRef } from 'react';
import { X, Download, FileText, Calendar, DollarSign } from 'lucide-react';
import { Card } from './ui/Card';
import { TermSheet } from '../types';

interface FullTermSheetProps {
  termSheet: TermSheet;
  companyName: string;
  onClose: () => void;
}

export const FullTermSheet: React.FC<FullTermSheetProps> = ({
  termSheet,
  companyName,
  onClose
}) => {
  const termSheetRef = useRef<HTMLDivElement>(null);

  const handleDownload = () => {
    // Create a simplified text version for download
    const content = `
TERM SHEET
${companyName}
Date: ${new Date().toLocaleDateString()}

══════════════════════════════════════════════════════

INVESTMENT TERMS

Investment Amount: ${termSheet.investmentAmount}
Valuation: ${termSheet.valuation}
Equity Stake: ${termSheet.equityPercentage}

══════════════════════════════════════════════════════

USE OF FUNDS

${Object.entries(termSheet.useOfFunds)
  .filter(([_, value]) => value && value !== "To be determined")
  .map(([key, value]) => `${key.charAt(0).toUpperCase() + key.slice(1)}: ${value}`)
  .join('\n')}

══════════════════════════════════════════════════════

TERMS & CONDITIONS

Board Seats: ${termSheet.terms.boardSeats || 'To be determined'}
Liquidation Preference: ${termSheet.terms.liquidationPreference || 'To be determined'}
Anti-Dilution: ${termSheet.terms.antiDilution || 'To be determined'}
Voting Rights: ${termSheet.terms.votingRights || 'To be determined'}
Pro-Rata Rights: ${termSheet.terms.proRataRights || 'To be determined'}

══════════════════════════════════════════════════════

MILESTONES

Revenue Target: ${termSheet.milestones.revenue || 'To be determined'}
Profitability Timeline: ${termSheet.milestones.profitability || 'To be determined'}
Customer Growth: ${termSheet.milestones.customerGrowth || 'To be determined'}

══════════════════════════════════════════════════════

NEXT STEPS

${termSheet.nextSteps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

══════════════════════════════════════════════════════

NOTES

${termSheet.notes || 'None'}

══════════════════════════════════════════════════════

This term sheet is generated by Founder AI and represents preliminary terms
discussed during the negotiation session. This is not a legally binding document.
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${companyName.replace(/\s+/g, '_')}_TermSheet_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/90 backdrop-blur-sm animate-fade-in overflow-y-auto">
      <Card className="w-full max-w-4xl my-8 relative" padding="none">
        {/* Header */}
        <div className="sticky top-0 bg-slate-900 border-b border-slate-700 p-4 flex items-center justify-between z-10">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-emerald-500/10 rounded-lg">
              <FileText className="w-5 h-5 text-emerald-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white font-display">Term Sheet</h2>
              <p className="text-sm text-slate-400">{companyName}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg font-semibold transition-all"
            >
              <Download size={18} />
              Download
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-slate-800 rounded-full transition-colors text-slate-400 hover:text-white"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Document Content */}
        <div ref={termSheetRef} className="p-8 bg-slate-950/50 space-y-8">
          {/* Header Section */}
          <div className="text-center pb-6 border-b border-slate-700">
            <h1 className="text-3xl font-bold text-white mb-2 font-display">TERM SHEET</h1>
            <p className="text-xl text-emerald-400 font-semibold">{companyName}</p>
            <div className="flex items-center justify-center gap-2 mt-3 text-slate-400 text-sm">
              <Calendar size={16} />
              <span>{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
            </div>
          </div>

          {/* Investment Terms */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-slate-700 flex items-center gap-2">
              <DollarSign className="w-5 h-5 text-emerald-400" />
              Investment Terms
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-slate-800/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm text-slate-400 mb-1">Investment Amount</p>
                <p className="text-lg font-bold text-white">{termSheet.investmentAmount}</p>
              </div>
              <div className="bg-slate-800/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm text-slate-400 mb-1">Valuation</p>
                <p className="text-lg font-bold text-white">{termSheet.valuation}</p>
              </div>
              <div className="bg-slate-800/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm text-slate-400 mb-1">Equity Stake</p>
                <p className="text-lg font-bold text-white">{termSheet.equityPercentage}</p>
              </div>
            </div>
          </section>

          {/* Use of Funds */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-slate-700">
              Use of Funds
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {Object.entries(termSheet.useOfFunds).map(([key, value]) => (
                value && value !== "To be determined" && (
                  <div key={key} className="bg-slate-800/50 p-3 rounded-lg border border-slate-700">
                    <p className="text-xs text-slate-400 capitalize mb-1">{key}</p>
                    <p className="text-sm font-semibold text-white">{value}</p>
                  </div>
                )
              ))}
            </div>
          </section>

          {/* Terms & Conditions */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-slate-700">
              Terms & Conditions
            </h2>
            <div className="space-y-3">
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Board Composition</p>
                <p className="text-white">{termSheet.terms.boardSeats || 'To be determined'}</p>
              </div>
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Liquidation Preference</p>
                <p className="text-white">{termSheet.terms.liquidationPreference || 'To be determined'}</p>
              </div>
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Anti-Dilution Provisions</p>
                <p className="text-white">{termSheet.terms.antiDilution || 'To be determined'}</p>
              </div>
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Voting Rights</p>
                <p className="text-white">{termSheet.terms.votingRights || 'To be determined'}</p>
              </div>
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Pro-Rata Rights</p>
                <p className="text-white">{termSheet.terms.proRataRights || 'To be determined'}</p>
              </div>
            </div>
          </section>

          {/* Milestones */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-slate-700">
              Performance Milestones
            </h2>
            <div className="space-y-3">
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Revenue Target</p>
                <p className="text-white">{termSheet.milestones.revenue || 'To be determined'}</p>
              </div>
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Profitability Timeline</p>
                <p className="text-white">{termSheet.milestones.profitability || 'To be determined'}</p>
              </div>
              <div className="bg-slate-800/30 p-4 rounded-lg border border-slate-700/50">
                <p className="text-sm text-slate-400 mb-1">Customer Growth Target</p>
                <p className="text-white">{termSheet.milestones.customerGrowth || 'To be determined'}</p>
              </div>
            </div>
          </section>

          {/* Next Steps */}
          {termSheet.nextSteps && termSheet.nextSteps.length > 0 && (
            <section>
              <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-slate-700">
                Next Steps
              </h2>
              <ol className="space-y-2">
                {termSheet.nextSteps.map((step, idx) => (
                  <li key={idx} className="flex gap-3 text-slate-300">
                    <span className="text-emerald-400 font-bold">{idx + 1}.</span>
                    <span>{step}</span>
                  </li>
                ))}
              </ol>
            </section>
          )}

          {/* Notes */}
          {termSheet.notes && termSheet.notes !== "To be determined" && (
            <section>
              <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-slate-700">
                Additional Notes
              </h2>
              <div className="bg-amber-950/20 border border-amber-500/20 p-4 rounded-lg">
                <p className="text-slate-300 text-sm leading-relaxed">{termSheet.notes}</p>
              </div>
            </section>
          )}

          {/* Disclaimer */}
          <div className="pt-6 border-t border-slate-700">
            <p className="text-xs text-slate-500 text-center leading-relaxed">
              This term sheet is generated by Founder AI and represents preliminary terms discussed during the negotiation session.
              <br />
              This is not a legally binding document and should be reviewed by legal counsel before execution.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
};
